# Generated by Django 3.2.12 on 2022-02-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0016_alter_crudevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
