# Generated by Django 3.2.12 on 2022-02-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0016_alter_crudevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='object_json_repr',
            field=models.JSONField(blank=True, null=True, verbose_name='Object JSON representation'),
        ),
    ]
