# Generated by Django 4.1.7 on 2023-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0017_alter_requestevent_datetime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crudevent',
            index=models.Index(fields=['-datetime'], name='easyaudit_c_datetim_a13040_idx'),
        ),
    ]
