# Generated by Django 5.0.1 on 2026-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easyaudit", "0019_alter_crudevent_changed_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crudevent",
            name="changed_fields",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Changed fields"
            ),
        ),
    ]
