# Generated by Django 5.0.1 on 2026-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easyaudit", "0020_alter_crudevent_changed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="crudevent",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Metadata"),
        ),
    ]
