# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='test data', max_length=50),
        ),
    ]
