# Generated by Django 2.2 on 2021-02-06 20:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_testbigintforeignkey_testbigintm2m_testbigintmodel_testuuidforeignkey_testuuidm2m_testuuidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSoftDeleteModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('some_other_field', models.CharField(default='', max_length=50)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
