# Generated by Django 5.2.17 on 2026-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_add_article_tag_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='HidableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test data', max_length=50)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
