# Generated by Django 5.0.1 on 2026-06-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_add_article_tag_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataAModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="metadata A", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MetadataBModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="metadata B", max_length=50)),
                (
                    "model_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.metadataamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetadataCModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="metadata C", max_length=50)),
                (
                    "model_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.metadatabmodel",
                    ),
                ),
            ],
        ),
    ]
