# Generated by Django 5.0.1 on 2026-06-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_metadata_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("tags", models.ManyToManyField(blank=True, to="test_app.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_app.place",
                    ),
                ),
            ],
            bases=("test_app.place",),
        ),
    ]
