name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, '3.10']
        django-version: [2.2, 2.2.8, 3.0, 3.1, 3.2]
        exclude:
          - python-version: 3.5
            django-version: 2.2.8
          - python-version: 3.5
            django-version: 3.0
          - python-version: 3.5
            django-version: 3.1
          - python-version: 3.5
            django-version: 3.2
          - python-version: 3.8
            django-version: 2.2
          - python-version: 3.10
            django-version: 2.2
          - python-version: 3.10
            django-version: 2.2.8
          - python-version: 3.10
            django-version: 3.0
          - python-version: 3.10
            django-version: 3.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install django==${{ matrix.django-version }}
        python -m pip install -e .
    - name: Run Tests
      run: |
        cd ./easyaudit/tests
        python -m manage test
